version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/openvidu-browser"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "deps"
      include: "scope"
    open-pull-requests-limit: 0      
    groups:
      production-dependencies:
        dependency-type: "production"
        applies-to: security-updates        
      development-dependencies:
        dependency-type: "development"
        applies-to: security-updates
    labels:
      - "nodejs"
      - "dependencies"
      - "security"
    assignees:
      - "jrx-jsj"
      - "jrx-fsj"
      - "jrx-amf"
      - "jrx-sjg"
  - package-ecosystem: "maven"
    directory: "/openvidu-server"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "deps"
      include: "scope"
    open-pull-requests-limit: 0      
    groups:
      production-dependencies:
        dependency-type: "production"
        applies-to: security-updates        
      development-dependencies:
        dependency-type: "development"
        applies-to: security-updates
    labels:
      - "java"
      - "dependencies"
      - "security"
    assignees:
      - "jrx-jsj"
      - "jrx-amf"
      - "jrx-sjg"  