{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "openvidu.serviceAccountName" . }}
  labels:
{{ include "openvidu.labels" . | indent 4 }}
{{- end -}}
