{{- if and (.Values.keda.enabled) (.Capabilities.APIVersions.Has "keda.sh/v1alpha1") }}
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: {{ include "openvidu.fullname" . }}-master-to-zero
spec:
  cooldownPeriod: {{- .Values.keda.coolDown }}
  minReplicaCount: {{- .Values.keda.minReplica }}
  pollingInterval: {{- .Values.keda.interval }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: {{ include "openvidu.fullname" . }}-master
  triggers:
  - metadata:
      desiredReplicas: "0"
      start: {{- .Values.keda.cron.start }}
      end: {{- .Values.keda.cron.end }}
      timezone: {{- .Values.keda.cron.timeZone }}
    type: cron
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: {{ include "openvidu.fullname" . }}-media-to-zero
spec:
  cooldownPeriod: {{- .Values.keda.coolDown }}
  minReplicaCount: {{- .Values.keda.minReplica }}
  pollingInterval: 30
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: {{ include "openvidu.fullname" . }}-media-node
  triggers:
  - metadata:
      desiredReplicas: "0"
      start: {{- .Values.keda.cron.start }}
      end: {{- .Values.keda.cron.end }}
      timezone: {{- .Values.keda.cron.timeZone }}
    type: cron    
{{- end }}