{{- if .Values.services.openvidu.pro.enabled }}
{{- if .Values.services.openvidu.pro.elasticsearch.enabled }}
apiVersion: beat.k8s.elastic.co/v1beta1
kind: Beat
metadata:
  name: {{ include "openvidu.fullname" . }}-metricbeat
  labels:
    app.kubernetes.io/name: {{ include "openvidu.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}  
spec:
  type: metricbeat
  version: {{ .Values.services.openvidu.pro.elasticsearch.version }}
  elasticsearchRef:
    name: {{ include "openvidu.fullname" . }}-elasticsearch
  kibanaRef:
    name: {{ include "openvidu.fullname" . }}-kibana
  config:
    setup:
      kibana:
        path: /kibana
    metricbeat:
      autodiscover:
        providers:
        - hints:
            default_config: {}
            enabled: "true"
          node: ${NODE_NAME}
          type: kubernetes
      modules:
      - module: system
        period: 10s
        metricsets:
        - cpu
        - load
        - memory
        - network
        - process
        - process_summary
        process:
          include_top_n:
            by_cpu: 5
            by_memory: 5
        processes:
        - .*
      - module: system
        period: 1m
        metricsets:
        - filesystem
        - fsstat
        processors:
        - drop_event:
            when:
              regexp:
                system:
                  filesystem:
                    mount_point: ^/(sys|cgroup|proc|dev|etc|host|lib)($|/)
      - module: kubernetes
        period: 10s
        node: ${NODE_NAME}
        hosts:
        - https://${NODE_NAME}:10250
        bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
        ssl:
          verification_mode: none
        metricsets:
        - node
        - system
        - pod
        - container
        - volume
    processors:
    - add_cloud_metadata: {}
    - add_host_metadata: {}
    output:
      elasticsearch:
        index: "%{[fields.log_type]}-%{+yyyy.MM.dd}"
  daemonSet:
    podTemplate:
      spec:
        serviceAccountName: {{ include "openvidu.fullname" . }}-metricbeat
        automountServiceAccountToken: true
        containers:
        - args:
          - -e
          - -c
          - /etc/beat.yml
          - -system.hostfs=/hostfs
          name: metricbeat
          volumeMounts:
          - mountPath: /hostfs/sys/fs/cgroup
            name: cgroup
          - mountPath: /var/run/docker.sock
            name: dockersock
          - mountPath: /hostfs/proc
            name: proc
          env:
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
        dnsPolicy: ClusterFirstWithHostNet
        hostNetwork: true
        securityContext:
          runAsUser: 0
        terminationGracePeriodSeconds: 30
        volumes:
        - hostPath:
            path: /sys/fs/cgroup
          name: cgroup
        - hostPath:
            path: /var/run/docker.sock
          name: dockersock
        - hostPath:
            path: /proc
          name: proc
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "openvidu.fullname" . }}-metricbeat
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  - namespaces
  - events
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - "extensions"
  resources:
  - replicasets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - statefulsets
  - deployments
  - replicasets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - nodes/stats
  verbs:
  - get
- nonResourceURLs:
  - /metrics
  verbs:
  - get
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "openvidu.fullname" . }}-metricbeat
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "openvidu.fullname" . }}-metricbeat
subjects:
- kind: ServiceAccount
  name: {{ include "openvidu.fullname" . }}-metricbeat
  namespace: default
roleRef:
  kind: ClusterRole
  name: {{ include "openvidu.fullname" . }}-metricbeat
  apiGroup: rbac.authorization.k8s.io          
---          
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: {{ include "openvidu.fullname" . }}-elasticsearch
  labels:
    app.kubernetes.io/name: {{ include "openvidu.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}  
spec:
  version: {{ .Values.services.openvidu.pro.elasticsearch.version }}
  volumeClaimDeletePolicy: DeleteOnScaledownOnly
  nodeSets:
  - name: default
    count: {{ .Values.services.openvidu.pro.elasticsearch.nodeCount }}
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: {{ .Values.services.openvidu.pro.elasticsearch.volumeSize }}
        storageClassName: {{ .Values.services.openvidu.pro.elasticsearch.storageClassName }}
    podTemplate:
      spec:
        initContainers:
          - name: sysctl
            securityContext:
              privileged: true
              runAsUser: 0
            command: ['sh', '-c', 'sysctl -w vm.max_map_count=262144'] 
  http:
    tls:
      selfSignedCertificate:
        disabled: true
---
apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: {{ include "openvidu.fullname" . }}-kibana
  labels:
    app.kubernetes.io/name: {{ include "openvidu.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}  
spec:
  version: {{ .Values.services.openvidu.pro.elasticsearch.version }}
  count: 1
  elasticsearchRef:
    name: {{ include "openvidu.fullname" . }}-elasticsearch
  config:
    server.basePath: "/kibana"
    server.rewriteBasePath: true
    {{- if .Values.services.openvidu.pro.elasticsearch.kibanaIngress.enabled }}
    server.publicBaseUrl: "https://{{ index .Values.services.openvidu.pro.elasticsearch.kibanaIngress.hosts 0 }}/kibana"
    {{- end }}
  http:
    tls:
      selfSignedCertificate:
        disabled: true
  podTemplate:
    spec:
      containers:
      - name: kibana        
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /kibana/login
            port: 5601
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
---
{{- if .Values.services.openvidu.pro.elasticsearch.kibanaIngress.enabled -}}
{{- $serviceName := include "openvidu.fullname" . -}}
{{- $servicePort := 5601 -}}
{{- $paths := .Values.services.openvidu.pro.elasticsearch.kibanaIngress.paths -}}
apiVersion: {{ template "openvidu.ingress.apiVersion" . }}
kind: Ingress
metadata:
  name: {{ include "openvidu.fullname" . }}-kibana
  labels:
    app: {{ .Chart.Name }}
    chart: {{ .Chart.Name }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  {{- range $key, $value := .Values.services.openvidu.pro.elasticsearch.kibanaIngress.labels }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- if .Values.services.openvidu.pro.elasticsearch.kibanaIngress.annotations }}
  annotations:
{{ toYaml .Values.services.openvidu.pro.elasticsearch.kibanaIngress.annotations | indent 4 }}
{{- end }}
spec:
  rules:
  {{- if .Values.services.openvidu.pro.elasticsearch.kibanaIngress.hosts }}
  {{- range $host := .Values.services.openvidu.pro.elasticsearch.kibanaIngress.hosts }}
    - host: {{ $host }}
      http:
        paths:
  {{- range $p := $paths }}
          - path: {{ $p }}
            pathType: ImplementationSpecific          
            backend:
              service:
                name:  {{ $serviceName }}-kibana-kb-http
                port:
                  number: {{ $servicePort }}
  {{- end -}}
  {{- end -}}
  {{- else }}
    - http:
        paths:
  {{- range $p := $paths }}
          - path: {{ $p }}
            pathType: ImplementationSpecific          
            backend:
              service:
                name:  {{ $serviceName }}-kibana-kb-http
                port:
                  number: {{ $servicePort }}
  {{- end -}}
  {{- end -}}
  {{- if .Values.services.openvidu.pro.elasticsearch.kibanaIngress.tls }}
  tls:
{{ toYaml .Values.services.openvidu.pro.elasticsearch.kibanaIngress.tls | indent 4 }}
  {{- end -}}
{{- end -}}
{{- end }}
{{- end }}