{{- if .Values.services.openvidu.pro.enabled }}
{{- if .Values.services.openvidu.pro.elasticsearch.enabled }}
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: {{ include "openvidu.fullname" . }}-elasticsearch
  labels:
    app.kubernetes.io/name: {{ include "openvidu.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}  
spec:
  version: {{ .Values.services.openvidu.pro.elasticsearch.version }}
  volumeClaimDeletePolicy: DeleteOnScaledownOnly
  nodeSets:
  - name: default
    count: {{ .Values.services.openvidu.pro.elasticsearch.nodeCount }}
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: {{ .Values.services.openvidu.pro.elasticsearch.volumeSize }}
        storageClassName: {{ .Values.services.openvidu.pro.elasticsearch.storageClassName }}
---
apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: {{ include "openvidu.fullname" . }}-kibana
  labels:
    app.kubernetes.io/name: {{ include "openvidu.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}  
spec:
  version: {{ .Values.services.openvidu.pro.elasticsearch.version }}
  count: {{ .Values.services.openvidu.pro.elasticsearch.nodeCount }}
  elasticsearchRef:
    name: {{ include "openvidu.fullname" . }}-elasticsearch
{{- end }}
{{- end }}