apiVersion: v2
name: openvidu-kubernetes
description: Jaraxa implementation of openvidu on Kubernetes
home: https://github.com/jaraxasoftware/openvidu-kubernetes/
version: 2.27.0
appVersion: 2.27.0
icon: https://jaraxa-public.s3.eu-central-1.amazonaws.com/LogoJRX-web.svg
maintainers:
- email: sergio.jurado@jaraxa.com
  name: Sergio Jurado
sources:
- https://github.com/openvidu/openvidu/