# Default values for openvidu.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
# optional list of image pull secrets to use to pull images
jx:
  # optional image pull secrets
  imagePullSecrets: []
  # whether to create a Release CRD when installing charts with Release CRDs included
  releaseCRD: true
test:
  enabled: false
serviceAccount:
  create: false
service:
  name: openvidu
  externalPort: 5443
# Mandatory. Can be deployment or distributed
mode: deployment
updateStrategy: OnDelete
services:
  openvidu:
    enabled: true
    type: master
    image:
      repository: openvidu/openvidu-server
      tag: 2.27.0
      pullPolicy: IfNotPresent
    port: 443
    configDir: /opt/openvidu/
    secret: openvidu
    pro:
      enabled: true
      license: xxxxxx-yyyyyy-zzzzzz-aaaaaa-bbbb
      cluster: true
      mode: manual
      environment: on_premise
      autoscaling: false
      loadStrategy: streams
      networkQoS: false
      masterReplicas: 1
      mediaNodeReplicas: 1
      mediaReconnTimeout: 5
      browserLogs: disabled
      monitoringInterval: 30
      elasticsearch:
        enabled: true
        version: 7.17.9
        nodeCount: 1
        volumeSize: 10Gi
        storageClassName: do-block-storage
        user: elastic
        password: changeme
        serviceType: ClusterIP
        daysRetention: 7
        kibanaIngress:
          enabled: false
          annotations: {}
          paths:
          - /kibana/
          hosts:
          - openvidu.localhost
          tls:
          - secretName: openvidu-secret
            hosts:
            - openvidu.localhost
        resources: {}
    protocols:
    - TCP
    ssl:
      enabled: false
      certType: owncert
    kms:
      uris:
      - "ws://localhost:8888/kurento"
    coturn:
      ip: localhost.openvidu
      port: 3478
      uris: "turn:localhost:3478?transport=tcp"
      iceServers: '["url=turn:localhost:3478,username=turn,credential=nknk"]'
      redis:
        ip: localhost-redis-master
        db: 1
        password: changeit
    bandwidth:
      received:
        max: 1000
        min: 300
      send:
        max: 1000
        min: 300
    recording:
      enabled: false
      debug: false
      path: /opt/openvidu/recordings
      layout: /opt/openvidu/custom-layout
      public: false
      notification: publisher_moderator
      autostop: 120
    transcoding:
      enabled: false
    webhook:
      enabled: true
      endpoint: http://localhost/api/v1/your_webhook/openvidu
      headers: ""
      events: '["sessionCreated", "sessionDestroyed", "participantJoined", "participantLeft", "webrtcConnectionCreated", "webrtcConnectionDestroyed", "recordingStatusChanged", "filterEventDispatched"]'
    gc:
      interval: 900
      threshold: 3600
    cdr:
      enabled: false
      path: /opt/openvidu/cdr
    env: {}
  media-node-controller:
    enabled: false
    type: media
    image:
      repository: openvidu/media-node-controller
      tag: 2.27.0
      pullPolicy: IfNotPresent
    protocols:
    - TCP
    port: 3000
    env: {}
  kms:
    enabled: true
    type: media
    image:
      repository: kurento/kurento-media-server
      tag: 7.0.1
      pullPolicy: IfNotPresent
    protocols:
    - TCP
    port: 8888
    env:
      KURENTO_LOGS_PATH: "/var/log/kurento-media-server/"
      KMS_MIN_PORT: "40000"
      KMS_MAX_PORT: "45000"
  logging:
    enabled: false
    type: monitoring
    image:
      repository: docker.elastic.co/beats/filebeat-oss
      tag: 7.17.9
      pullPolicy: IfNotPresent
  metricbeat:
    enabled: false
    type: monitoring
    image:
      repository: docker.elastic.co/beats/metricbeat-oss
      tag: 7.17.9
      pullPolicy: IfNotPresent
  openvidu-call:
    enabled: false
    type: test
    image:
      repository: openvidu/openvidu-call
      tag: 2.27.0
      pullPolicy: IfNotPresent
    protocols:
    - TCP
    port: 5442
    env: {}
keda:
  enabled: false
  coolDown: 30
  interval: 30
  cron:
    start: 00 15 * * *
    end: 15 15 * * *
    timeZone: Europe/Madrid
  annotations: {}
  extraTriggers: {}
ingress:
  enabled: false
  annotations: {}
  paths:
  - /(.*)
  hosts:
  - openvidu.localhost
  tls:
  - secretName: openvidu-secret
    hosts:
    - openvidu.localhost
livenessProbe:
  initialDelaySeconds: 60
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 1
  failureThreshold: 3
readinessProbe:
  initialDelaySeconds: 60
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 1
  failureThreshold: 3
resourcesPro:
  master: {}
  media: {}
  monitoring: {}
resources: {}
securityContext: {}
nodeSelector: {}
tolerations: []
affinity: {}
image:
  repository: ghcr.io/jaraxasoftware/openvidu-kubernetes
  tag: 2.27.0-1702368843678
