# Default values for openvidu.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1

# optional list of image pull secrets to use to pull images
jx:
  # optional image pull secrets
  imagePullSecrets: []

  # whether to create a Release CRD when installing charts with Release CRDs included
  releaseCRD: true

serviceAccount:
  create: false

service:
  name: openvidu
  externalPort: 5443

services:
  openvidu:
    enabled: true
    image: 
      repository: openvidu/openvidu-server
      tag: 2.27.0
      pullPolicy: IfNotPresent
    port: 443
    configDir: /opt/openvidu/
    secret: openvidu
    pro:
      enabled: false
      license: xxxxxx-yyyyyy-zzzzzz-aaaaaa-bbbb
      cluster: true
      mode: manual
      environment: on_premise
      autoscaling: false
      loadStrategy: streams
      elasticsearch: 
        enabled: false
        version: 7.17.9
        nodeCount: 1
        volumeSize: 10Gi
        storageClassName: do-block-storage
        user: elastic
        password: changeme
        serviceType: ClusterIP
        kibanaIngress:
          enabled: false
          annotations: {}
          paths:
            - /kibana/
          hosts:
            - openvidu.localhost
          tls:
            - secretName: openvidu-secret
              hosts:
                - openvidu.localhost        
      networkQoS: false
    protocols:
      - TCP
    ssl:
      enabled: false
      certType: owncert
    kms:
      uris: '["ws://localhost:8888/kurento"]'
    coturn:
      ip: localhost.openvidu
      port: 3478
      uris: "turn:localhost:3478?transport=tcp"
      iceServers: '["url=turn:localhost:3478,username=turn,credential=nknk"]'
      redis:
        ip: localhost-redis-master
        db: 1
        password: changeit
    bandwidth:
      received:
        max: 1000
        min: 300
      send:
        max: 1000
        min: 300
    recording:
      enabled: false
      debug: false
      path: /opt/openvidu/recordings
      layout: /opt/openvidu/custom-layout
      public: false
      notification: publisher_moderator
      autostop: 120
    transcoding:
      enabled: false
    webhook:
      enabled: true
      endpoint: http://localhost/api/v1/your_webhook/openvidu
      headers: ""
      events: '["sessionCreated", "sessionDestroyed", "participantJoined", "participantLeft", "webrtcConnectionCreated", "webrtcConnectionDestroyed", "recordingStatusChanged", "filterEventDispatched"]'
    gc:
      interval: 900
      threshold: 3600
    cdr: 
      enabled: false
      path: /opt/openvidu/cdr
    env: {}

  media-node-controller:
    enabled: false
    image: 
      repository: openvidu/media-node-controller
      fixed_tag: 2.27.0
      pullPolicy: IfNotPresent
    port: 3000
    protocols:
      - TCP    
    env: {}

  kms:
    enabled: true
    image: 
      repository: kurento/kurento-media-server
      fixed_tag: 7.0.1
      pullPolicy: IfNotPresent
    env:
      KURENTO_LOGS_PATH: "/var/log/kurento-media-server/"
      KMS_MIN_PORT: "40000"
      KMS_MAX_PORT: "45000"

  logging:
    enabled: false
    image: 
      repository: docker.elastic.co/beats/filebeat-oss
      fixed_tag: 7.17.9
      pullPolicy: IfNotPresent

  metricbeat:
    enabled: false
    image: 
      repository: docker.elastic.co/beats/metricbeat-oss
      fixed_tag: 7.17.9
      pullPolicy: IfNotPresent

  openvidu-call:
    enabled: false
    image: 
      repository: openvidu/openvidu-call
      fixed_tag: 2.27.0
      pullPolicy: IfNotPresent
    protocols:
      - TCP        
    port: 5442
    env: {}

ingress:
  enabled: false
  annotations: {}
  paths:
    - /(.*)
  hosts:
    - openvidu.localhost
  tls:
    - secretName: openvidu-secret
      hosts:
        - openvidu.localhost

livenessProbe:
  initialDelaySeconds: 60
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 1
  failureThreshold: 3
readinessProbe:
  initialDelaySeconds: 60
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 1
  failureThreshold: 3

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
