apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  creationTimestamp: null
  name: develop
spec:
  pipelineSpec:
    tasks:
    - name: openvidu-kubernetes
      resources: {}
      taskSpec:
        metadata: {}
        stepTemplate:
          env:
          - name: BUILD_VERSION
            value: -DEVELOP
          - name: ENVIRONMENT
            value: dkv-develop
          image: uses:jaraxasoftware/jaraxa-pipeline-catalog/tasks/helm/release.yaml@versionStream
          name: ""
          resources: {}
          workingDir: /workspace/source
        steps:
        - image: uses:jaraxasoftware/jaraxa-pipeline-catalog/tasks/git-clone/git-clone.yaml@versionStream
          name: ""
          resources: {}
        - name: next-version
          script: |
            #!/usr/bin/env sh
            echo $BUILD_VERSION-$BUILD_ID >> VERSION
        - name: jx-variables
          resources: {}
        - image: node:18-slim
          name: build-npm-version
          script: |
            #!/bin/bash
            source .jx/variables.sh
            cd openvidu-browser
            npm install
            npm --no-git-tag-version version $VERSION           
        - image: node:18-slim
          name: openvidu-browser-build
          script: |
            #!/usr/bin/env bash
            source .jx/variables.sh
            cd openvidu-browser
            echo "Building openvidu-browser"
            npm run build
            npm run browserify
        - image: node:18-slim
          name: build-npm-publish
          script: |
            #!/bin/bash
            source .jx/variables.sh
            cd openvidu-browser
            npm publish               
        - name: chart-docs
          resources: {}    
        - name: promote-changelog-uat
          resources: {}
          script: |
            #!/usr/bin/env sh
            set -v
            source .jx/variables.sh
            if [ -d "charts/$REPO_NAME" ]; then
            jx gitops yset -p version -v "$VERSION" -f ./charts/$REPO_NAME/Chart.yaml
            jx gitops yset -p appVersion -v "$VERSION" -f ./charts/$REPO_NAME/Chart.yaml
            else echo no charts; fi       
        - name: promote-helm-release
          resources: {}
        - name: promote-jx-promote
          resources: {}
        volumes:
        - name: npmrc
          secret:
            optional: true
            secretName: npmrc-nexus          
  podTemplate: {}
  serviceAccountName: tekton-bot
  timeout: 12h0m0s
status: {}
