apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  creationTimestamp: null
  name: pullrequest
spec:
  pipelineSpec:
    tasks:
    - name: from-build-pack
      resources: {}
      taskSpec:
        metadata: {}
        stepTemplate:
          env:
          - name: BUILD_VERSION
            value: -PR
          image: uses:jaraxasoftware/jaraxa-pipeline-catalog/tasks/helm/pullrequest.yaml@versionStream
          name: ""
          resources:
            # override limits for all containers here
            limits: {}
          workingDir: /workspace/source
        steps:
        - image: uses:jaraxasoftware/jaraxa-pipeline-catalog/tasks/git-clone/git-clone-pr.yaml@versionStream
          name: ""
          resources: {}
        - name: jx-variables
          resources:
            # override requests for the pod here
            requests:
              cpu: 400m
              memory: 512Mi
        - name: next-version
          script: |
            #!/usr/bin/env sh
            echo $BUILD_VERSION-$BUILD_ID >> VERSION              
        - image: node:14-slim
          name: build-npm-version
          script: |
            #!/bin/bash
            source .jx/variables.sh
            cd openvidu-browser
            npm install
            npm --no-git-tag-version version $VERSION
        - image: node:14-slim
          name: openvidu-browser-build
          script: |
            #!/usr/bin/env bash
            source .jx/variables.sh
            cd openvidu-browser
            echo "Building openvidu-browser"
            npm run build
            npm run browserify                          
        - name: promote-jx-preview
          resources: {}
  podTemplate: {}
  serviceAccountName: tekton-bot
  timeout: 12h0m0s
status: {}
